# Generated by Django 3.2.2 on 2021-05-12 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Título')),
                ('date_post', models.DateField(default=django.utils.timezone.now, verbose_name='Data da postagem')),
                ('content_post', models.TextField(verbose_name='Conteudo')),
                ('excerpt_post', models.TextField(verbose_name='Excerto')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('publicated_post', models.BooleanField(default=False, verbose_name='Publicado')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categorie', verbose_name='Cátegoria')),
            ],
        ),
    ]
